<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Duende.IdentityModel.OidcClient" Version="6.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Cookies" Version="2.3.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.13" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.OpenIdConnect" Version="8.0.13" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" Version="8.0.13" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="8.0.1" />
    <PackageReference Include="System.DirectoryServices.AccountManagement" Version="8.0.1" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Pages\Probation\" />
    <Folder Include="Pages\Offer\" />
    <Folder Include="Pages\Service\Form\" />
    <Folder Include="Pages\Service\Dashboard\" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="_verify_obj\**" />
    <Content Remove="_verify_obj\**" />
    <EmbeddedResource Remove="_verify_obj\**" />
    <None Remove="_verify_obj\**" />
  </ItemGroup>

</Project>
